<a href="https://colab.research.google.com/github/Ndiyaf/Latihan-Github/blob/main/MP1_Pertemuan4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import numpy dulu
import numpy as np

#Cek versi NumPy yang terinstall
print(np.__version__)

2.0.2


In [20]:
#Array 1 Dimensi (1D) versi angka
arr_id = np.array([10, 20, 30, 50])
print (arr_id)

#Array 1 Dimensi (1D) versi nama
nama_student = np.array([ "Nindi, Widya, Sheyla"])
print(nama_student)

[10 20 30 50]
['Nindi, Widya, Sheyla']


In [ ]:
#Array 2 Dimensi (2D) — seperti tabel/matriks
arr_2d = np.array([
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

print(arr_2d)

In [ ]:
#Array berisi nol
np.zeros(n)

#Array berisi satu
np.ones(n)

#Array rentang angka
np.arange(start,stop,step)

#N titik merata antara start-stop
np.linspace(start,stop,n)

#Array bilangan acak bulat
np.random.randint(low,high,n)

#Array bilangan acak 0.0–1.0
np.random.rand(n)

In [9]:
#Array berisi nol
#versi 2d nya

nol = np.zeros((3, 3))
print(nol)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
angka = np.random.randint(5, 51, 10) * 5

print(angka)

[ 45 155  95 180 125  60 120 110  65 175]


In [23]:
kelipatan = np.arange (5,45,5) #1 Dimensi
kelipatan_2d = kelipatan.reshape (4,2) #RESHAPE : DIUBAH BENTUK MENJADI 2 DIMENSI
print(kelipatan_2d)

[[ 5 10]
 [15 20]
 [25 30]
 [35 40]]


In [25]:
data = np.array([10, 20, 30, 40, 50])

#mean : mencari rata-rata
print("rata-rata : ", np.mean(data))
#max : mencari nilai tertinggi
print(" nilai tertinggi : ", np.max(data))
#min : mencari nilai terendah
print(" nilai terandah : ", np.min(data))
#sum : mencari total array
print("total array : ", np.sum(data))
#median : menjadi nilai tengah
print("nilai tengah : ", np.median(data))
#standar deviasi : std
print("std : ", np.std(data))

rata-rata :  30.0
 nilai tertinggi :  50
 nilai terandah :  10
total array :  150
nilai tengah :  30.0
std :  14.142135623730951


In [ ]:
# Operasi array vs skalar (angka tunggal)
nilai = np.array([75, 85, 90, 65, 80])

print(nilai + 5)
# [80 90 95 70 85] → semua ditambah 5

print(nilai * 2)
# [150 170 180 130 160]

print(nilai / 100)
# [0.75 0.85 0.9  0.65 0.8]

print(nilai ** 2)
# [5625 7225 8100 4225 6400]


# Operasi antar dua array (elemen per elemen)
uts = np.array([70, 80, 85, 60, 75])
uas = np.array([80, 90, 95, 70, 85])

nilai_akhir = (uts * 0.4) + (uas * 0.6)

print(nilai_akhir)
# [76. 86. 91. 66. 81.]

In [32]:
#OPERASI ARITMATIKA
tinggi = np.array([155, 162, 170, 158, 165]) #INDEX DI MULAI DARI 0

#155
print(tinggi[0])
#162
print(tinggi[-1])

155
165


In [29]:
#SLICING
tinggi = np.array([155, 162, 170, 158, 165]) #INDEX DI MULAI DARI 0
#162,170
#155
print(tinggi[1:3]) #[INDEX KE(dibaca dari 0), DATA KE(dibaca dari 1)]
#162
print(tinggi[0:3])

# Format: arr[slice_baris, slice_kolom]
nilai = np.array([
    [85, 90, 78, 88],
    [92, 75, 95, 80],
    [70, 85, 65, 90],
    [88, 92, 70, 85]
])

print(nilai[0, :])      # [85 90 78 88]    → semua nilai baris 0
print(nilai[:, 0])      # [85 92 70 88]    → semua nilai kolom 0
print(nilai[1:3, 1:3])  # [[75 95],[85 65]] → sub-matriks

[162 170]
[155 162 170]


In [35]:
#Format: arr[start:stop:step]
angka = np.arange(10, 60, 5)   #[10 15 20 25 30 35 40 45 50 55]

#angka awal, sampai index ke, muncul dengan kelipatan
print(angka)

print(angka[2:6])
print(angka[:4])
print(angka[6:])
print(angka[::2])

[10 15 20 25 30 35 40 45 50 55]
[20 25 30 35]
[10 15 20 25]
[40 45 50 55]
[10 20 30 40 50]


In [ ]:
#MENCOBA
arr3 = np.array([
    [22, 23, 24],
    [25, 26, 27],
    [28, 29, 30]
])

# [BARIS, KOLOM]

In [41]:
# TUGAS PERTEMUAN 4
# ARRAY DATA TINGGI BADAN 10 SISWA

import numpy as np


# DATA SISWA

# Array 1D tinggi badan 10 siswa (cm)
data_tinggi = np.array([
    165, 170, 158, 172, 162,
    175, 168, 180, 155, 170
])

# Array 1D berat badan 10 siswa (kg)
data_berat = np.array([
    58, 63, 50, 68, 55,
    72, 60, 75, 48, 65
])

# Array 2D: 10 siswa x 2 kolom
# Kolom 0 = tinggi
# Kolom 1 = berat
data_siswa = np.array([
    [165, 58],
    [170, 63],
    [158, 50],
    [172, 68],
    [162, 55],
    [175, 72],
    [168, 60],
    [180, 75],
    [155, 48],
    [170, 65]
])

# 1. ATRIBUT ARRAY 2D

print("ATRIBUT ARRAY DATA SISWA")
print("Shape :", data_siswa.shape)
print("Ndim  :", data_siswa.ndim)
print("Dtype :", data_siswa.dtype)
print("Size  :", data_siswa.size)


# 2. INDEXING

print()
print("INDEXING")

# Tinggi badan siswa ke-1 (index 0)
print("Tinggi siswa ke-1 :", data_tinggi[0], "cm")

# Berat badan siswa ke-7 (index 6)
print("Berat siswa ke-7  :", data_berat[6], "kg")

# Data lengkap siswa ke-5 (index 4)
print("Data siswa ke-5   :", data_siswa[4])


# 3. SLICING

print()
print("SLICING")

# Tinggi badan 5 siswa pertama
print("Tinggi 5 siswa pertama :", data_tinggi[:5])

# Berat badan 3 siswa terakhir
print("Berat 3 siswa terakhir :", data_berat[-3:])

# Data siswa ke-3 sampai ke-7
print("Data siswa ke-3 sampai ke-7 :")
print(data_siswa[2:7])

# 4. OPERASI ARITMATIKA DAN KATEGORI IMT

# Mengubah tinggi dari cm menjadi meter
tinggi_m = data_tinggi / 100

# Menghitung IMT semua siswa
imt = data_berat / (tinggi_m ** 2)

# Menentukan kategori IMT menggunakan if-elif-else
kategori = []

for nilai in imt:
    if nilai < 18.5:
        kategori.append("Kurus")
    elif nilai < 25:
        kategori.append("Normal")
    elif nilai < 30:
        kategori.append("Gemuk")
    else:
        kategori.append("Obesitas")

# 5. TABEL REKAP

print()
print("REKAP DATA SISWA + IMT")
print("No  Tinggi  Berat   IMT    Kategori")
print("--------------------------------------")

for i in range(10):
    print(
        f"{i+1:<3} "
        f"{data_tinggi[i]:<7} "
        f"{data_berat[i]:<7} "
        f"{imt[i]:<6.2f} "
        f"{kategori[i]}"
    )

ATRIBUT ARRAY DATA SISWA
Shape : (10, 2)
Ndim  : 2
Dtype : int64
Size  : 20

INDEXING
Tinggi siswa ke-1 : 165 cm
Berat siswa ke-7  : 60 kg
Data siswa ke-5   : [162  55]

SLICING
Tinggi 5 siswa pertama : [165 170 158 172 162]
Berat 3 siswa terakhir : [75 48 65]
Data siswa ke-3 sampai ke-7 :
[[158  50]
 [172  68]
 [162  55]
 [175  72]
 [168  60]]

REKAP DATA SISWA + IMT
No  Tinggi  Berat   IMT    Kategori
--------------------------------------
1   165     58      21.30  Normal
2   170     63      21.80  Normal
3   158     50      20.03  Normal
4   172     68      22.99  Normal
5   162     55      20.96  Normal
6   175     72      23.51  Normal
7   168     60      21.26  Normal
8   180     75      23.15  Normal
9   155     48      19.98  Normal
10  170     65      22.49  Normal
